/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurahsRouteImport } from './routes/surahs'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurahIdRouteImport } from './routes/surah/$id'

const SurahsRoute = SurahsRouteImport.update({
  id: '/surahs',
  path: '/surahs',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahIdRoute = SurahIdRouteImport.update({
  id: '/surah/$id',
  path: '/surah/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/progress': typeof ProgressRoute
  '/search': typeof SearchRoute
  '/surahs': typeof SurahsRoute
  '/surah/$id': typeof SurahIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/progress': typeof ProgressRoute
  '/search': typeof SearchRoute
  '/surahs': typeof SurahsRoute
  '/surah/$id': typeof SurahIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/progress': typeof ProgressRoute
  '/search': typeof SearchRoute
  '/surahs': typeof SurahsRoute
  '/surah/$id': typeof SurahIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/progress'
    | '/search'
    | '/surahs'
    | '/surah/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bookmarks' | '/progress' | '/search' | '/surahs' | '/surah/$id'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/progress'
    | '/search'
    | '/surahs'
    | '/surah/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  ProgressRoute: typeof ProgressRoute
  SearchRoute: typeof SearchRoute
  SurahsRoute: typeof SurahsRoute
  SurahIdRoute: typeof SurahIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surahs': {
      id: '/surahs'
      path: '/surahs'
      fullPath: '/surahs'
      preLoaderRoute: typeof SurahsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surah/$id': {
      id: '/surah/$id'
      path: '/surah/$id'
      fullPath: '/surah/$id'
      preLoaderRoute: typeof SurahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  ProgressRoute: ProgressRoute,
  SearchRoute: SearchRoute,
  SurahsRoute: SurahsRoute,
  SurahIdRoute: SurahIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
